- ngx-forge.module.ts
- src/app/components/project-select/project-select.component.html
- src/app/components/project-select/project-select.component.less
- src/app/components/sanitize/sanitize.url.pipe.ts
if the runtime has an icon use that otherwise use the class as before see https://github.com/fabric8-launcher/launcher-planning/issues/73
> added support for runtime icon

- src/app/launcher/gitprovider-step/gitprovider-step.component.html
- src/app/launcher/gitprovider-step/gitprovider-step.component.ts
- src/app/launcher/model/github.model.ts
- src/app/launcher/service/gitprovider.service.ts
- src/demo/service/demo-gitprovider.service.ts
To test, select runtime, mission, and version. Then select the "Authorize Account" button from the "Authorize Git Provider" step.
After authorizing with GitHub, and redirecting back to the demo, the user's avatar, user name, and "Change Account" button are shown in the "Authorize Git Provider" step.
Note: Access-Conrtol-Expose-Headers must be enabled for CORS. Otherwise, the demo cannot retrieve the user's GitHub token. This won't be the case for OSIO as REST APIs exist for this.
> gitprovider: added auth functionality to launch demo

- src/app/launcher/launcher.module.ts
- src/app/launcher/step-indicator/step-indicator.component.html
- src/app/launcher/step-indicator/step-indicator.component.ts
- src/app/launcher/step-indicator/step.ts
- src/app/launcher/wizard-step.ts
- src/app/launcher/wizard.component.html
- src/app/launcher/wizard.component.ts
Simplified how steps are hidden and shown via the HTML template. The two 'next steps" are now shown (mutually exclusive) based on the target environment selection.
> chore(app-launcher): simplified how steps are shown

- src/app/launcher/model/selection.model.ts
- src/app/launcher/model/summary.model.ts
- src/app/launcher/step-indicator/step-indicator.component.html
- src/app/launcher/step-indicator/step-indicator.component.ts
- src/app/launcher/wizard.component.ts
This enables the inline-editable feature for the application title. It also restores the application title when returning from GitHub auth.
> app-launcher: add inline-editable application title feature

- config/webpack.demo.js
- src/app/launcher/activate-booster/activate-booster.component.html
- src/app/launcher/gitprovider-step/gitprovider-step.component.html
- src/app/launcher/gitprovider-step/gitprovider-step.component.ts
- src/app/launcher/launcher.module.ts
- src/app/launcher/mission-runtime-step/mission-runtime-step.component.ts
- src/app/launcher/model/mission.model.ts
- src/app/launcher/model/runtime.model.ts
- src/app/launcher/model/selection.model.ts
- src/app/launcher/model/summary.model.ts
- src/app/launcher/project-summary-step/project-summary-step.component.html
- src/app/launcher/project-summary-step/project-summary-step.component.less
- src/app/launcher/project-summary-step/project-summary-step.component.ts
- src/app/launcher/release-strategy-step/release-strategy-step.component.ts
- src/app/launcher/service/gitprovider.service.ts
- src/app/launcher/service/project-summary.service.ts
- src/app/launcher/step-indicator/step-indicator.component.html
- src/app/launcher/step-indicator/step-indicator.component.ts
- src/app/launcher/targetenvironment-step/target-environment-step.component.html
- src/app/launcher/targetenvironment-step/target-environment-step.component.ts
- src/app/launcher/wizard.component.ts
- src/demo/app.module.ts
- src/demo/service/demo-gitprovider.service.ts
- src/demo/service/demo-mission-runtime.service.ts
- src/demo/service/demo-project-summary.service.ts
- Removed hard coded HTML for pipeline, mission, runtime, github values from summary page.
- User can now inline edit application info; group ID, app name, app version, & space path.
- Dynamically show navigation buttons for incomplete pipeline and git provider steps.
- Save and restore values properly upon page refresh due to git authorization.
- Once expected selections are made, users are no longer forced to click Ok button in order to proceed to next step.
- Simplified up git provider in order to show correct state in summary page.
- Fixed broken images (demo/webpack) shown for summary, mission/runtime pages.
> app-launcher: added functionality to summary page

- package-lock.json
- package.json
Running into PR build failures with fabric8-ui (build:prod) due to inconsistent package versions. In particular, building with node 6.9.1 is causing “out of memory” errors.
To resolve these issues, I've matched the versions of Angular, Typescript, PatternFly, patternfly-ng, etc. I also noticed the ngx-forge package is still references node 6.9.1 instead of 8.3.0 which is used by fabric8-ui.
> chore(app-launcher): matched pkg versions with fabric8-ui

- src/app/launcher/mission-runtime-step/mission-runtime-step.component.html
- src/app/launcher/wizard.component.html
- src/demo/service/demo-mission-runtime.service.ts
Rearranged card order for the mission and runtime screen, per UXD feedback.
Added missing (mock) description text for missions.
> app-launcher: rearranged card order for mission and runtime screen

- package.json
- src/app/launcher/cancel-overlay/cancel-overlay.component.html
- src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.ts
- src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.ts
- src/app/launcher/launcher.component.ts
- src/demo/getting-started/getting-started.component.html
- src/demo/service/demo-git-provider.service.ts
- The cancel overlay is calling cancelAbort regardless if the user confirms or aborts.
- The github provider step is not reloading the app-launcher with the correct url.
> chore(app-launcher): fixed cancel overlay and github provider

- gulpfile.js
- package-lock.json
- package.json
- src/app/components/input/input.component.ts
- src/app/components/project-select/project-select.component.ts
- src/app/launcher/cancel-overlay/cancel-overlay.component.ts
- src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.html
- src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.html
- src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.html
- src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.html
Fixes: https://github.com/fabric8-launcher/ngx-launcher/issues/93
Tested via npm link with fabric8-ui.
Benefits:
- While the ngx-forge.js bundle is still available, these changes help fabric8-ui build performance because Angular isn’t resolving duplicates.
- Allows fabric8-ui to install its own dependencies instead of packages being duplicated by the ngx-forge.js bundle.
- Eliminates the ‘multiple mobx instances’ error seen with fabric8-ui unit tests, since certain dependencies are duplicated by the ngx-forge.js bundle.
Changes:
- Copied HTML and CSS to the correct dist/src/app directories instead of dist/app
- Copied missing images directory to dist/src/assets
- Modified package.json module to use index.js
- Fixed components with missing HTML and CSS paths
- Moved styleUrls after …
> app-launcher: modified ngx-forge package module to use index.js

- src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.html
- src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.less
- src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.spec.ts
- src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.html
- src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.html
- src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.less
- src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.html
- src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.html
- src/assets/stylesheets/shared/_labels.less
This addresses an issue with empty/dummy CSS selectors introduced for the mission & runtime unit tests.
Currently, these selectors do not exist:
- f8launcher-contribute-tag-label
- f8launcher-suggested-tag-label
- f8launcher-prerequisite-tag-label
> app-launcher: cleanup empty CSS selectors

- package-lock.json
- package.json
- src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.spec.ts
- src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.spec.ts
- src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.spec.ts
- src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.ts
- src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.ts
- src/app/launcher/launcher.module.ts
- src/vendor.ts
Updated the patternfly-ng package version to match what's used in fabric8-ui.
Also taking advantage of the new patternfly-ng modules so we only import what we need in the UI.
> app-launcher: update patternfly-ng version to match fabric8-ui

- src/demo/service/demo-mission-runtime.service.ts
Appends a query param (?runsOn) on both Missions and Runtimes API calls to fetch results relevant to OSIO.
> changes the url to take in runsOn query parameter to filter the results only for specific environment

- package.json
- src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.ts
- src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.html
- src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.ts
- src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.html
- gitHub Provider View Location drop-down should show User's ID as the default
- hides artifactID in case of OSIO
- updates version to 0.0.69-development 
Issues : https://github.com/openshiftio/openshift.io/issues/2942
> gitHub Provider View Location drop-down should show User's ID as the default

- src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.html
- src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.html
- src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.less
- src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.html
- src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.less
- src/assets/stylesheets/shared/_labels.less
- src/assets/stylesheets/shared/_pipelines.less
fix(ux): changes the styles of tags
As per UX, the styles of tags have to be changed. This is how it will look once this PR will get merged.
fix(bug): handles the pipeline summary view bug
In Pipeline card of the summary tab, the pipelines look distorted. This happens if you select a pipeline with more number of stages.
And this PR handles that and after mer
ging, the card will look like below
> fix(ux): changes the styles of tags

- src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.html
Tracks: https://github.com/openshiftio/openshift.io/issues/2936
@mindreeper2420 Currently, in the Project summary screen, we have pipelines card and they are collapsed by default.
That shows a lot of empty space. 
~~This PR handles that by making it expanded by default and removing the option of toggling.~~
~~The reason for this is as this is the Summary screen, it would be good to show the whole information. Please let me know about the change.~~
Based on feedback from Brian in the issue linked, 
In case there are pipelines, the class 'card-pf--small' gets removed so that the height gets adjusted to the content's height.
Toggling feature is available.
> remove the card-pf--small class from pipelines card in case there are pipelines

- src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.html
Runtime has icons/images associated next to it to visually indicate the runtimes.
This PR adds them.
> fix(image): put back the image for runtime screen

- src/app/launcher/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.html
- src/app/launcher/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.ts
On the progress page, when all steps complete, a new section replace the steps.
This section inform the user on what he can do next with the location of his new github/openshift project.
Closes https://github.com/fabric8-launcher/launcher-frontend/issues/303
> feat: add next steps when deploying on openshift

- src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.html
- src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.spec.ts
- src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.ts
- src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.ts
- src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.html
- src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.spec.ts
- src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.ts
- src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.ts
- src/app/launcher/step-indicator/step-indicator.component.ts
- Handled validation for setup App Button in summary screen i.e Setup should be disabled if ProjectName, GroupID, Version, ArtifactID is not valid
- Issue with two way binding issue for repoName and app name
- Adds tests for git provider component
Tracks : 
https://github.com/openshiftio/openshift.io/issues/3548
> fix(summary): validation for summary screen

- src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts
Selected mission not available for the specific runtime we'll show another not availble sign. So we return true in this case.
fixes: https://github.com/fabric8-launcher/launcher-frontend/issues/359
> fix: mission not available so no check for runs on cluster.

- src/app/launcher/create-app/link-accounts-createapp-step/link-accounts-createapp-step.component.html
- src/app/launcher/create-app/link-accounts-createapp-step/link-accounts-createapp-step.component.less
- src/app/launcher/create-app/link-accounts-createapp-step/link-accounts-createapp-step.component.ts
- src/app/launcher/model/cluster.model.ts
- src/app/launcher/service/token.service.ts
- src/demo/service/demo-target-environment.service.ts
- src/demo/service/demo-token.service.ts
- Align buttons to the right of the screen
- Sort already authorized first
- Change label to "Authorize" instead of "Add"
- Make only one call to get the cluster list
BREAKING CHANGES:
- Added `connected: boolean` to `Cluster` model
- Remove `availableClusters` method from TokenService interface
Closes #217
> fix: improve cluster authorization

- src/app/launcher/create-app/link-accounts-createapp-step/link-accounts-createapp-step.component.spec.ts
- src/app/launcher/create-app/targetenvironment-createapp-step/target-environment-createapp-step.component.spec.ts
There were errors in tests because `availableClusters` have been removed from `TokenService`.
> fix: npm test

- config/webpack.demo.js
- package.json
fix(build): fixes error that happens during npm start of standalone launcher.
fix(version): updates fabric8-analytics-dependency-editor to 0.0.10
> fix(build): fixes error that happens during npm start of standalone launcher.

- src/app/launcher/create-app/dependency-editor-step/dependency-editor-step.component.ts
When you select a runtime first and then a mission version will be undefined
fixes https://github.com/fabric8-launcher/launcher-frontend/issues/366
> fix: version can be undefined

- src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.html
- src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts
Missions, when they have no runtimes that run selected cluster need to be deactived
fixes: https://github.com/fabric8-launcher/launcher-frontend/issues/375
> fix: missions need to be deactivated

- package-lock.json
- package.json
Upversion `ngx-base` and `fabric8-analytics-dependency-editor` to the latest that include fixes for peer dependencies.
Moving all dependencies and peerDependencies to use the `^` range. As a library, as long as the dependencies installed by the application meet the API needs of the library, the library should not force a particular version on the application (assuming semantic versioning is used). If doing so the application must package multiple versions of the library which is not ideal. By using the `^`, the library accepts any API compatible version and the application can instead bundle a single version of the library.
@edewit If there's a specific reason this was changed back to not use `^` please share.
> fix(versions): upversion and fix deps range

- src/app/launcher/create-app/link-accounts-createapp-step/link-accounts-createapp-step.component.ts
- src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts
- src/app/launcher/create-app/targetenvironment-createapp-step/target-environment-createapp-step.component.html
- src/app/launcher/create-app/targetenvironment-createapp-step/target-environment-createapp-step.component.ts
- step is completed only if "os and cluster" are selected or "zip".
- clusters are now fetched in `TargetEnvironmentCreateappStepComponent` and passed as input to `LinkAccountsCreateappStepComponent`.
- unsubscribe to broacaster event in `MissionRuntimeCreateappStepComponent`.
> fix: target env selection invalid completion and optimized clusters fetching

- src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts
- src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.model.ts
Make sure that disabled/not-loaded missions and runtimes are not selectable.
Closes https://github.com/fabric8-launcher/launcher-frontend/issues/478
> fix: TypeError: Cannot read property 'id' of undefined in MissionRuntimeCreateappStepComponent

- package.json
Reverts fabric8-launcher/ngx-launcher#291 as it didn't do what was intended.
> Revert "fix(version-fix): removed the caret in version"

- package-lock.json
- package.json
For some reason, prod-preview appears to be pulling an older version of patternfly-ng. This will ensure the sortArray pipe still works properly with the deprecated PipeModule.
> patternfly-ng: restore exports for deprecated PipeModule

- src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts
- src/app/launcher/model/booster.model.ts
- src/app/launcher/model/catalog.model.ts
- src/app/launcher/service/mission-runtime.service.spec.ts
- src/app/launcher/service/mission-runtime.service.ts
Add `metadata.suggested` in versions.
Use the `MissionRuntimeService.compareVersions` sort algo to render versions in a specific order:
- first suggested
- then community (it's a workaround until runtime teams use suggested)
- then reverse natural order
Pre-selected version is the first one.
Add a unit test.
BREAKING-CHANGE:
- remove `MissionRuntimeService.getDefaultVersion` which became useless with the sort algo
Closes #313
> fix: clean version selection code for launch flow

- src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.html
- src/app/launcher/shared/project-name.validator.spec.ts
- src/app/launcher/shared/project-name.validator.ts
- Updates regex for project name validation not to allow "no continuous '-' or '_' is allowed" and "should not end with trailing -"
- Updates error style for the summary screen in create flow as it's there for import flow
> fix(project-validation): updates the regex and error style

- package-lock.json
- package.json
- src/app/launcher/create-app/dependency-editor-step/dependency-editor-step.component.html
- src/app/launcher/create-app/dependency-editor-step/dependency-editor-step.component.spec.ts
- src/app/launcher/create-app/dependency-editor-step/dependency-editor-step.component.ts
1. This PR is to make the broadcaster instance available in the dependency editor module.
2. Depends on https://github.com/fabric8-analytics/fabric8-analytics-dependency-editor/pull/111. This is merged now
3. Need to update the dep-editor version once point 2 is merged and a new version is release successfully
> fix(telemetry): pass broadcaster instance to dep editor component

- package-lock.json
- package.json
Updates version of fabric8-analytics-dependency-editor to 0.7.4
- Avoids duplication of dependencies in added dependencies
- Avoids duplication of dependencies in core dependencies
> fix(version): updates version of dep editor

- src/app/launcher/create-app/dependency-editor-step/dependency-editor-step.component.html
- src/app/launcher/create-app/dependency-editor-step/dependency-editor-step.component.ts
- src/app/launcher/launcher.component.html
- src/app/launcher/launcher.component.spec.ts
Added a check to the dependency-editor-step-component to load the depenency-editor component only if feature flag is enabled.
> fix(dep-checker): calls dep editor component only if it's enabled

- src/app/launcher/cancel-overlay/cancel-overlay.component.html
- src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.spec.ts
- src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts
- src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.model.ts
- src/app/launcher/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.html
- src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.html
- src/app/launcher/create-app/release-strategy-createapp-step/pipelines.fixture.spec.ts
- src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.html
- src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.spec.ts
- src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.ts
- src/app/launcher/import-app/project-progress-importapp-nextstep/project-progress-importapp-nextstep.component.html
- src/app/launcher/import-app/project-progress-importapp-nextstep/project-progress-importapp-nextstep.component.spec.ts
- src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.html
- src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.html
- src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.spec.ts
- src/app/launcher/launcher.component.html
- src/app/launcher/model/pipeline.model.ts
- src/app/launcher/service/mission-runtime.service.spec.ts
- src/app/launcher/step-indicator/step-indicator.component.html
Pipeline selection is loaded once when the Step is initialized and always defaults to `maven` runtime. This blocks usage of other runtimes such as `nodejs`.
* broadcasts event on runtime change with pipeline platform specified
* pipeline selection step observes on it and updates pipeline selection
* if changed runtime has different pipeline platform it will reset the selection
Part of openshiftio/openshift.io#4140
Respective changes on fabric8-ui https://github.com/fabric8-ui/fabric8-ui/pull/3242
> fix: pipeline selection reacts on the runtime change

- src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.html
- src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.spec.ts
To see the auto-change behavior:
1- Deployment: zip
2- Choose runtime `Node` with version `10.x (RHOAR)`
3- Choose mission `Istio - Circuit Breaker`
=> Version has changed to 8.x `(Community)`
Fixes https://github.com/fabric8-launcher/launcher-frontend/issues/648
> fix: show version dropdown when runtime is selected

- projects/ngx-launcher/src/lib/components/runtime-step/runtime-step.component.ts
fixes: https://github.com/fabric8-launcher/launcher-frontend/issues/785
> fix: use unique name to store creator runtime name will override the mission-runtime
