fabric8-launcher/ngx-launcher

src/app/service/forge.service.ts
src/app/service/token-provider.ts

fix(headers); to include keycloak headers

---

src/app/model/base.model.ts

option have key and id

---

.gitignore
.s2i/bin/assemble
.s2i/bin/run
.s2i/bin/save-artifacts
.s2i/environment
README.md
package.json

This allows deployment and building on openshift for the demo app

Add s2i support for wizard demo

---

src/app/launcher/gitprovider-step/gitprovider-step.component.html
src/app/launcher/gitprovider-step/gitprovider-step.component.ts
src/app/launcher/launcher.module.ts
src/app/launcher/model/runtime.model.ts
src/app/launcher/model/user-selection.model.ts
src/app/launcher/service/gitprovider.service.ts
src/app/launcher/wizard.component.ts
src/demo/app.module.ts
src/demo/service/demo-gitprovider.service.ts

Added initial GitHub provider service

GitHub provider service

---

index.ts
package.json
src/app/launcher/service/gitprovider.service.ts
src/demo/service/demo-gitprovider.service.ts

Fix exports and sync package versions with platform UI

Launcher: fix exports

---

src/app/launcher/mission-runtime-step/mission-runtime-step.component.html
src/app/launcher/release-strategy-step/release-strategy-step.component.html
src/app/launcher/step-indicator/step-indicator.component.less
src/app/launcher/wizard.component.less
src/assets/stylesheets/shared/_labels.less

- Add support for up to 10 items in the Step Indicator
- Updates 'Suggested' label to include info icon
- Improve highlights and animations of the Step Indicator
- Add Complete/Warning icons for the Step Indicator, activated by adding the `.complete` or `.warning` classes to the `.f8launcher-step-circle` element.

fix(launcher): update step indicator and visual alignment

---

index.ts
package.json
src/app/launcher/gitprovider-step/gitprovider-step.component.html
src/app/launcher/gitprovider-step/gitprovider-step.component.ts
src/app/launcher/launcher.module.ts
src/app/launcher/mission-runtime-step/mission-runtime-step.component.html
src/app/launcher/mission-runtime-step/mission-runtime-step.component.ts
src/app/launcher/project-summary-step/project-summary-step.component.html
src/app/launcher/project-summary-step/project-summary-step.component.ts
src/app/launcher/release-strategy-step/release-strategy-step.component.html
src/app/launcher/release-strategy-step/release-strategy-step.component.ts
src/app/launcher/step-indicator/step-indicator.component.html
src/app/launcher/step-indicator/step-indicator.component.ts
src/app/launcher/step-indicator/step.ts
src/app/launcher/targetenvironment-step/target-environment-step.component.html
src/app/launcher/targetenvironment-step/target-environment-step.component.ts
src/app/launcher/wizard.component.html
src/app/launcher/wizard.component.ts
src/demo/components/welcome.component.ts

Ok button is now enabled if step is completed.
Clicking on the Ok button will navigate to the next uncompleted step -- try skipping a step.
Some steps remain hidden until both mission/runtime and target env are completed.
Clicking the summary OK button now shows “next steps” progress as full a page.

App-launcher: modified step indicator to navigate to next step

---

package.json
src/app/launcher/project-summary-step/project-summary-step.component.ts
src/app/launcher/step-indicator/step.ts
src/app/launcher/wizard.component.html
src/app/launcher/wizard.component.ts

Hide/show pipelines based on target env selection. Also showing steps based on a list of dependencies (previously completed steps).

app-launcher: hide/show pipelines based on target env selection

---

index.ts
package.json
src/app/launcher/gitprovider-step/gitprovider-step.component.ts
src/app/launcher/mission-runtime-step/mission-runtime-step.component.ts
src/app/launcher/project-summary-step/project-summary-step.component.ts
src/app/launcher/release-strategy-step/release-strategy-step.component.ts
src/app/launcher/step-indicator/step-indicator.component.html
src/app/launcher/step-indicator/step-indicator.component.ts
src/app/launcher/targetenvironment-step/target-environment-step.component.ts
src/app/launcher/wizard-step.ts
src/app/launcher/wizard.component.html
src/app/launcher/wizard.component.ts

Steps now extend wizard-step class.
This allows each step to register itself with the wizard. It also removes the previously hard coded step array in the wizard component.

app-launcher: added wizard-step class

---

src/app/launcher/gitprovider-step/gitprovider-step.component.html
src/app/launcher/mission-runtime-step/mission-runtime-step.component.html
src/app/launcher/project-summary-step/project-summary-step.component.html
src/app/launcher/release-strategy-step/release-strategy-step.component.html
src/app/launcher/step-indicator/step-indicator.component.ts
src/app/launcher/targetenvironment-step/target-environment-step.component.html
src/app/launcher/wizard.component.html
src/app/launcher/wizard.component.ts

Various step navigation fixes:
- Set initial step selection. 
- The onInViewportChange event doesn't always set the step ID as expected.
- Step components should hide themselves based on their given hidden input property

app-launcher: step navigation fixes

---

src/app/launcher/project-summary-step/project-summary-step.component.html
src/app/launcher/step-indicator/step-indicator.component.html
src/app/launcher/step-indicator/step-indicator.component.less

Note that the check mark still needs a little CSS work -- Adam will clean that up.

app-launcher: added check mark to completed steps

---

src/app/launcher/activate-booster/activate-booster.component.html
src/app/launcher/project-summary-step/project-summary-step.component.html
src/app/launcher/step-indicator/step-indicator.component.html
src/app/launcher/step-indicator/step-indicator.component.ts

This allows the app title to be updated via the step indicator and/or the project summary. The updated title is also shown on the zip progress page.
The inline-edit style will have to be fixed by Adam.

App title fix

---

src/app/launcher/mission-runtime-step/mission-runtime-step.component.html
src/app/launcher/mission-runtime-step/mission-runtime-step.component.ts

Clicking on the reset button performs a radio button reset and removes the users selection from the summary

app-launcher: implemented mission/runtime reset button

---

src/app/launcher/project-progress/project-progress.component.html
src/app/launcher/project-progress/project-progress.component.less

Update the Project Summary page to use the pfng list styles (new PatternFly list). Update checks and classes accordingly.

fix(summary): Update Summary to use pfng list styles

---

src/app/launcher/step-indicator/step-indicator.component.less
src/app/launcher/wizard.component.less

Update the step indicator styles to match the visuals designs found here: https://redhat.invisionapp.com/d/main#/console/12879000/276623587/preview.
Clean up code organization.

fix(steps): Update step styles to match visuals

---

config/webpack.demo.js
package.json
src/app/launcher/launcher.module.ts
src/app/launcher/model/pipeline.model.ts
src/app/launcher/release-strategy-step/release-strategy-step.component.html
src/app/launcher/release-strategy-step/release-strategy-step.component.less
src/app/launcher/release-strategy-step/release-strategy-step.component.ts
src/demo/service/demo-pipeline.service.ts

This introduces the patternfly-ng toolbar to provide filtering and sorting functionality to the pipeline page. In addition, the rows now expand and collapse when the arrow icon is toggled.

app-launcher: added filter, sort & expand/collapse functionality to pipelines

---

src/app/launcher/gitprovider-step/gitprovider-step.component.html
src/app/launcher/mission-runtime-step/mission-runtime-step.component.html
src/app/launcher/project-summary-step/project-summary-step.component.html
src/app/launcher/project-summary-step/project-summary-step.component.less
src/app/launcher/release-strategy-step/release-strategy-step.component.html
src/app/launcher/release-strategy-step/release-strategy-step.component.less
src/app/launcher/step-indicator/step-indicator.component.html
src/app/launcher/targetenvironment-step/target-environment-step.component.html
src/app/launcher/wizard.component.html
src/app/launcher/wizard.component.less
src/assets/stylesheets/shared/_cards.less

* Add extendable classes for the content. IDs are no longer needed for proper spacing, as it has been replaced with a set of 3 classes.
* Clean up various spots that used an overabundance of stylelint comments.
* Standardize a set of classes for input styles to include the single line, pencil icon on hover and blue underline highlight.
* Update card columns to include classes for GitHub user icons vs runtime icons.

Extensibility and Visual Upgrades

---

index.ts
package.json

These exports will be needed for use in OSIO.

app-launcher: added model and service exports to index.js

---

package.json
src/app/launcher/gitprovider-step/gitprovider-step.component.html
src/app/launcher/launcher.module.ts

- Replaced inline toast notification with help text per UXD review
- Bumped version to 0.0.44-development

app-launcher: replaced inline toast notification with help text

---

src/app/launcher/mission-runtime-step/mission-runtime-step.component.less
src/app/launcher/mission-runtime-step/mission-runtime-step.component.ts
src/app/launcher/project-summary-step/project-summary-step.component.html

- Added opacity for disabled image per UXD request
- Added cancel button to summary page per UXD request
- Fix empty dropdown selection when runtime is disabled

app-launcher: fixes per UXD review

---

src/app/launcher/gitprovider-step/gitprovider-step.component.html
src/app/launcher/gitprovider-step/gitprovider-step.component.ts
src/app/launcher/mission-runtime-step/mission-runtime-step.component.html

After the user authorizes GitHub, and the page is refreshed, focus should be set on the organization select menu. This should help make it clear there is more to complete for this step.

chore(app-launcher): set focus after github authorization

---

src/app/components/pipeline-view/pipeline-view.component.html
src/app/components/pipeline-view/pipeline-view.component.spec.ts
src/app/launcher/launcher.component.spec.ts

Fixes https://github.com/openshiftio/openshift.io/issues/2281

fix: display pipeline name for radio box

---

src/app/launcher/activate-booster/activate-booster.component.spec.ts
src/app/launcher/gitprovider-step/gitprovider-step.component.spec.ts
src/app/launcher/launcher.component.spec.ts
src/app/launcher/mission-runtime-step/mission-runtime-step.component.spec.ts
src/app/launcher/project-progress/project-progress.component.spec.ts
src/app/launcher/project-summary-step/project-summary-step.component.spec.ts
src/app/launcher/release-strategy-step/release-strategy-step.component.spec.ts
src/app/launcher/step-indicator/step-indicator.component.spec.ts
src/app/launcher/targetenvironment-step/target-environment-step.component.spec.ts

Fixes scaffold test cases for existing components.
Signed-off-by: invinciblejai <mailjai.vardhan@gmail.com>

fixes scaffolding tests

---

package.json
src/app/launcher/cancel-overlay/cancel-overlay.component.html
src/app/launcher/cancel-overlay/cancel-overlay.component.less
src/app/launcher/cancel-overlay/cancel-overlay.component.ts
src/app/launcher/create-app/activate-booster-createapp-nextstep/activate-booster-createapp-nextstep.component.ts
src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.html
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.html
src/app/launcher/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.html
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.html
src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.html
src/app/launcher/create-app/targetenvironment-createapp-step/target-environment-createapp-step.component.html
src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.html
src/app/launcher/import-app/project-progress-importapp-nextstep/project-progress-importapp-nextstep.component.html
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.html
src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.html
src/app/launcher/launcher.component.html
src/app/launcher/launcher.component.spec.ts
src/app/launcher/launcher.component.ts
src/app/launcher/launcher.module.ts
src/demo/getting-started/getting-started.component.ts

Created initial cancel-overlay component. Also added the "getting started" overlay to the demo.
Adam will apply HTML and CSS.

chore(app-launcher): added cancel overlay

---

src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.ts
src/app/launcher/launcher.component.ts
src/app/launcher/launcher.module.ts
src/app/launcher/model/runtime.model.ts
src/app/launcher/model/selection.model.ts
src/demo/service/demo-mission-runtime.service.ts
src/demo/service/demo-pipeline.service.ts

Various fixes required for fabric8-ui to build properly.
- Fixed missing HelperService export
- Renamed incorrect runtime platform property to pipelinePlatform
- Fixed missing semi-colons
- Fixed ts-lint errors with spacing and indentation

app-launcher: various fixes for fabric8-ui

---

src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.html
src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.less
src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.html
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.ts
src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.html
src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.less
src/app/launcher/launcher.component.html
src/app/launcher/model/github-details.model.ts
src/demo/service/demo-git-provider.service.ts

related to https://github.com/fabric8-ui/fabric8-ux/issues/893

feat(import): Update Import steps to match designs

---

src/app/launcher/create-app/activate-booster-createapp-nextstep/activate-booster-createapp-nextstep.component.spec.ts
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.spec.ts
src/app/launcher/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.spec.ts
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.spec.ts
src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.spec.ts
src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.ts
src/app/launcher/create-app/targetenvironment-createapp-step/target-environment-createapp-step.component.spec.ts

- fixes ts lint errors
- fixes broken test for pipelines spec
- handles accordion on pipeline to open in single click
Signed-off-by: invinciblejai <mailjai.vardhan@gmail.com>

fix pipeline test and ts lint fix

---

src/app/launcher/launcher.component.less
src/app/launcher/step-indicator/step-indicator.component.less

Update the step bar styles after user testing to fix issues.

fix(steps): update step bar after user testing

---

package-lock.json
package.json
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts
src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.html
src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.ts
src/app/launcher/create-app/targetenvironment-createapp-step/target-environment-createapp-step.component.ts
src/app/launcher/launcher.component.html
src/app/launcher/launcher.component.less
src/app/launcher/launcher.component.ts
src/app/launcher/step-indicator/step-indicator.component.ts

- OSIO to show all steps, except target environment
- Launcher continues to hide steps until target environment is selected
- Increased screen spacing to fix selection issues on OSIO
- Continue button selects next step instead of next uncompleted step
- Removed toolbar from pipelines
- Pipelines expanded by default
- Fixed missing default platform value (for pipelines) when page is reloaded
- bumped package version to 0.0.50-development

app-launcher: added flag to show all steps for OSIO

---

package-lock.json
package.json
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.html
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.html
src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.html
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.html
src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.html

- Added popover outsideClick event to dismiss popovers
- Enabled select anywhere within a mission & runtime list item

app-launcher: dismissible popovers and select anywhere

---

config/webpack.prod.js
gulpfile.js
package-lock.json
src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.spec.ts
tsconfig.json

This addresses a build performance issue with fabric-ui where the ngx-forge.js bundle is too large.
Also removed demo files from dist directory

chore(app-launcher): webpack uglify for tree shaking

---

src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.spec.ts
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.html
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.spec.ts
src/app/launcher/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.spec.ts
src/app/launcher/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.ts
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.spec.ts
src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.spec.ts
src/app/launcher/create-app/targetenvironment-createapp-step/target-environment-createapp-step.component.spec.ts
src/app/launcher/model/mission.model.ts
src/app/launcher/model/runtime.model.ts

1. Introduces unit tests for mission
2. Introduces unit tests for runtimes
3. Introduces unit tests for pipelines
4. Introduces unit tests for github flow
5. Introduces unit tests for project summary
6. Introduces unit tests for project progress
7. Introduces unit tests for target environment
With this change, introduced unit tests will be run on each PR and merge builds to make sure things are stable.

Unit tests for all screen components (Quick starts - Getting started flow)

---

src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.html
src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.ts
src/app/launcher/model/github-details.model.ts
src/app/launcher/service/git-provider.service.ts
src/demo/service/demo-git-provider.service.ts

- service  changes for git screen
- Handles error block for git
- introduces a new method to get GitHub Repos for Organization/Owner

fix(service): fixes github  services for import flow

---

.gitignore
package.json
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.html
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.ts
src/app/launcher/launcher.component.ts
src/app/launcher/service/project-summary.service.ts
src/demo/service/demo-dependency-check.service.ts
src/demo/service/demo-project-summary.service.ts

fix(get-space-metadata): Fetch the space metadata from context service

---

src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.ts
src/app/launcher/import-app/project-progress-importapp-nextstep/project-progress-importapp-nextstep.component.html
src/app/launcher/import-app/project-progress-importapp-nextstep/project-progress-importapp-nextstep.component.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.ts
src/app/launcher/launcher.component.html
src/app/launcher/service/project-summary.service.ts
src/demo/service/demo-project-summary.service.ts

- Added services for summary screen for import flow
- Logic to show the status messages for the progress screen in the import flow.

fix(import-service): Added the summary and progress service for the import flow

---

src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.ts
src/app/launcher/service/project-summary.service.ts
src/demo/service/demo-project-summary.service.ts

fix(service): avoid osio services directly

---

src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.html
src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.less
src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.ts
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.html
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.spec.ts
src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.html
src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.less
src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.spec.ts
src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.ts
src/app/launcher/import-app/project-progress-importapp-nextstep/project-progress-importapp-nextstep.component.spec.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.html
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.spec.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.ts
src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.html
src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.spec.ts
src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.ts
src/app/launcher/launcher.component.html
src/app/launcher/launcher.module.ts

This PR fixes : 
- Updates GitHub screen as per UXD for Import/Quickstarts
- Introduces typeahead for repository select box in Import flow
- Removes Optional from pipelines
- Fixes broken test in project-summary
- Change repo status check flow (for existing repo) in Quickstart
- Adds tests for component of Import flow

fix(import-flow): updates gitHub screen as per UXD

---

package.json

This version upgrade handles
1. Github screens modified as per latest UXD
2. Show the error messages if any in the progress step
3. Style improvements

fix(version-upgrade): Upgraded to 0.0.62-development

---

package.json

this upgrade takes care of some bug fixes

fix(version): Upgraded to version 0.0.63-development

---

src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.html
src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.ts
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.ts
src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.html
src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.ts
src/app/launcher/import-app/project-progress-importapp-nextstep/project-progress-importapp-nextstep.component.html
src/app/launcher/import-app/project-progress-importapp-nextstep/project-progress-importapp-nextstep.component.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.html
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.ts

code refactoring and improvement

fix(code-improvement): code refactoring and improvement

---

package.json

upgraded to 0.0.64-development
- contains code improvements

fix(version): upgraded to 0.0.64-development

---

src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.spec.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.spec.ts
src/demo/service/demo-dependency-check.service.ts

updates default values for artifact, groupID, version.

fix(service): updates default values for artifact, groupID, version

---

src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.html
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.less
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.spec.ts

Runtime and Missions Screen (https://redhat.invisionapp.com/share/VGF1RF15J#/screens/286894929)
- updates description/ show more as per UXD
- removes runtime icon
- updates tests

fix(runtime-mission): fixes description as per UXD, updates tests

---

src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.html

Adds Application Info in summary view of import as per UXD.

fix(import-summary) adds Application Info in summary view of import

---

src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts

fixes issue with runtime/mission selection on reload post authorization with gitHub.
fix for: https://github.com/fabric8-launcher/ngx-launcher/issues/125

fix(issue): fixes issue with runtime/mission selection on reload

---

src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.less
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.html
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.html
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.ts

- makes artifact editable
- sets default values in component

fix(summary): makes artifact editable, sets default values in component

---

package.json

This upgrade contains the following changes
- Set default values for artifactid , groupId and version
- Updates to the summary screen in the import flow as per UXD
- Handled inconsistency in selection of mission and runtime after redirecting from github step

fix(version): upgraded to 0.0.65-development

---

src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.less
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.less
src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.less

- updates text alignment to left for labels in pipelines/summary screen

fix(alignment) : updates text alignment to left for labels

---

package.json

Upgraded to 0.0.66-development

fix(version): upgraded to 0.0.66-development

---

src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.ts

- adds timestamp to make artifactId unique

fix(artifactid): adds timestamp to make artifactId unique

---

src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.html
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.html
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.ts
src/app/launcher/launcher.component.ts
src/app/launcher/model/dependency-check.model.ts
src/app/launcher/service/dependency-check.service.ts
src/app/launcher/step-indicator/step-indicator.component.html
src/app/launcher/step-indicator/step-indicator.component.less
src/app/launcher/step-indicator/step-indicator.component.ts
src/demo/service/demo-dependency-check.service.ts

Added validation for 
- Project Name in all the applicable screens.
- Project Version in summary screen
- Maven artifact in summary screen
- Group Id in summary screen

fix(validation): Added validation logic for Project name

---

src/app/launcher/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.html
src/app/launcher/import-app/project-progress-importapp-nextstep/project-progress-importapp-nextstep.component.html
src/demo/getting-started-osio/getting-started-osio.component.html
src/demo/getting-started-osio/getting-started-osio.component.less
src/demo/getting-started-osio/getting-started-osio.component.ts

- swap Quickstart card with Import in the overlay screen
- adds button in progress screen as per UXD

fix(ux-changes): swap Quickstart card with Import in overlay

---

package.json

This version contains :-
- https://github.com/fabric8-launcher/ngx-launcher/pull/138
- https://github.com/fabric8-launcher/ngx-launcher/pull/134
- https://github.com/fabric8-launcher/ngx-launcher/pull/133

fix(version): upgraded to 0.0.67-development

---

src/app/launcher/create-app/targetenvironment-createapp-step/target-environment-createapp-step.component.ts
src/app/launcher/model/selection.model.ts

fix(targetenvironment): adds checks, tslint

---

src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.less

Tracks https://github.com/openshiftio/openshift.io/issues/2935

puts the text over the stages of the pipeline in center (horizontally)

---

package.json
src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.html
src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.spec.ts
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.html
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.less
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.spec.ts
src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.html

- Handles layout issue on click of more in the description
- Fixes tests
- Change fonts for the description
- Truncating to 55 characters as font-size reduced
Issues : https://github.com/openshiftio/openshift.io/issues/2821

fix(issues): handles layout issue on click of more in description

---

Jenkinsfile
cico_run_tests.sh
release.groovy

fix(cicd): introduced files for cicd and semantic release setup

---

package.json

Includes
remove the card-pf--small class from pipelines card in case there are pipelines
fix(bug): handles the pipeline summary view bug
fix(ux): changes the styles of tags
fix(cicd): updates to fix cicd
fix(bug): added nodejs install script
fix(cicd): introduced files for cicd and semantic release setup

fix(version): updates package.json to 0.0.73-development

---

package.json
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.html
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.less
src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.html
src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.less

Handles style related changes for tags in import flow
Handles pipelines empty space in summary screen - import flow
fix(version): updates version to 0.0.74-development

fix(style): handles the tag style changes for import flow 

---

package.json
src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.html
src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.ts

- adds validation on reponame
Tracks: https://github.com/openshiftio/openshift.io/issues/3022

fix(github): adds validation on reponame

---

src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.ts

- Setup/Import button does not allow us to click and proceed at times

fix(bug): Setup/Import button does not work at times

---

package.json
src/app/launcher/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.ts
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.ts
src/app/launcher/import-app/project-progress-importapp-nextstep/project-progress-importapp-nextstep.component.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.ts
src/app/launcher/service/project-progress.service.ts
src/app/launcher/service/project-summary.service.ts
src/demo/service/demo-project-progress.service.ts
src/demo/service/demo-project-summary.service.ts

This fixes the issue where a user was not able to click the Import/Create button in the Summary screen in the New Getting Started flow.

fix(bug): Import/Create button does not allow us to create a application

---

src/assets/stylesheets/shared/_cards.less

- Removed extra space from Select Mission Runtime step

fix(bug): Removed extra space from Select Mission Runtime step

---

README.md

updated readme to test the release process

fix(readme): updated readme

---

src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.html
src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.less

Tracks: https://github.com/openshiftio/openshift.io/issues/3091

fix(bug): corrects tooltip's width on hover.

---

src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.html
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.less
src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.html
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.html
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.less
src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.html
src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.less

Tracks: https://github.com/openshiftio/openshift.io/issues/3091

fix(bug): corrects tooltip hover misalignment on import flow and project summary space of create flow

---

src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts

fixes: https://github.com/fabric8-launcher/launcher-frontend/issues/312

fix: only add timestamp for osio

---

README.md

Updated readme to test the build and releas

fix(semantic): update readme file

---

cico_setup.sh

fix(CI/CD): Remove REFRESH_TOKEN

---

src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.html
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.less
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.html
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.less

Update the Project Summary anchor to be on the button container; increase the size of the Set Up Application button.

fix(summary): Update project summary anchor and button

---

src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.html
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.less

Changes the text for Suggests and Contribute.
Handles the style for the same in Missions and Runtimes screen

fix(design): changes the style of the tag in mission and runtimes screen

---

src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts

Tracks: https://github.com/openshiftio/openshift.io/issues/3370

fix(bug): corrects unusual disable problems with missions and runtimes radio selections.

---

src/demo/service/demo-mission-runtime.service.ts
src/demo/service/demo-pipeline.service.ts
src/demo/service/demo-project-progress.service.ts
src/demo/service/demo-project-summary.service.ts

in order to quickly make visual changes to the launcher it's easier if mock data is returned. This PR changes services back to do that.

Back to demo

---

src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.ts
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.html
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.ts
src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.ts
src/app/launcher/step-indicator/step-indicator.component.html
src/app/launcher/step-indicator/step-indicator.component.ts

- binding app name and repo name as a workaround for duplicate builds in OSIO
Tracks : 
https://github.com/openshiftio/openshift.io/issues/3432

fix(pipelines): binding app name and repo name

---

src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts

Fixes issue with the version on the selection of runtime first

fix(runtime): issue with version on selection of runtime first

---

src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.html
src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.ts
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.html
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.ts
src/app/launcher/step-indicator/step-indicator.component.html
src/app/launcher/step-indicator/step-indicator.component.ts

Tracks: https://github.com/openshiftio/openshift.io/issues/3411

fix(case): changes the application name and git repository name of create flow to be lowercase to maintain consistency due to issues in build

---

src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.html
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts
src/assets/stylesheets/shared/_labels.less

- introduces community badge for mission
Tracks: 
https://github.com/openshiftio/openshift.io/issues/3453

feat(community): introduces community badge for mission

---

src/app/launcher/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.html
src/app/launcher/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.less

fixes: https://github.com/fabric8-launcher/launcher-frontend/issues/343

fix: next step text

---

package-lock.json
package.json
src/app/launcher/create-app/link-accounts-createapp-step/link-accounts-createapp-step.component.html
src/app/launcher/create-app/link-accounts-createapp-step/link-accounts-createapp-step.component.less
src/app/launcher/create-app/link-accounts-createapp-step/link-accounts-createapp-step.component.spec.ts
src/app/launcher/create-app/link-accounts-createapp-step/link-accounts-createapp-step.component.ts
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.html
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts
src/app/launcher/create-app/targetenvironment-createapp-step/target-environment-createapp-step.component.html
src/app/launcher/create-app/targetenvironment-createapp-step/target-environment-createapp-step.component.less
src/app/launcher/create-app/targetenvironment-createapp-step/target-environment-createapp-step.component.spec.ts
src/app/launcher/create-app/targetenvironment-createapp-step/target-environment-createapp-step.component.ts
src/app/launcher/launcher.component.html
src/app/launcher/model/runtime.model.ts
src/app/launcher/service/mission-runtime.service.ts
src/demo/app.module.ts
src/demo/service/demo-mission-runtime.service.ts
src/demo/service/demo-token.service.ts

Selecting a cluster for "launch" is now more close to the new design:
https://redhat.invisionapp.com/share/67HOQB7UCB9#/screens/294121665

Made target environment the first step

---

src/app/launcher/launcher.component.ts

@jyasveer fix for regression found in #204

fix: instead of selecting the first step select the first non hidden.

---

src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.ts
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.html
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.ts
src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.html
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.ts
src/app/launcher/launcher.component.spec.ts
src/app/launcher/launcher.component.ts
src/app/launcher/service/dependency-check.service.ts
src/app/launcher/step-indicator/step-indicator.component.html
src/app/launcher/step-indicator/step-indicator.component.ts
src/demo/service/demo-dependency-check.service.ts

- Don't allow a user to enter a existing application name.
- Checks if the repo name is also unique and not a existing application name.
Addresses :- https://github.com/openshiftio/openshift.io/issues/3399

fix(duplicate-app-name): Block a user from entering a duplicate app name

---

README.md

Updated readme to trigger build

fix(trigger-build): updated readme to trigger build

---

src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.html
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.spec.ts
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.html
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.spec.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.ts
src/app/launcher/launcher.module.ts
src/app/launcher/toast-notification/toast-notification.component.html
src/app/launcher/toast-notification/toast-notification.component.less
src/app/launcher/toast-notification/toast-notification.component.ts

- adds toast notification in case of error for setup app
Tracks : https://github.com/openshiftio/openshift.io/issues/3513

feat(setup): adds toast notification in case of error for setup app

---

src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.html

@ia3andy removes the pipeline section for "launch"

fix: pipeline should only be displayed for osio

---

package-lock.json
src/app/launcher/create-app/link-accounts-createapp-step/link-accounts-createapp-step.component.html

fix: avoid to repeat "OpenShift (<clusterId>)" in cluster selection

---

src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts
src/app/launcher/model/runtime.model.ts
src/demo/service/demo-mission-runtime.service.ts

@quintesse new `metadata` structure

fix: more complex meta data structure

---

src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.ts
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.ts
src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.ts
src/app/launcher/launcher.component.ts
src/app/launcher/step-indicator/step-indicator.component.ts

Addresses :- https://github.com/openshiftio/openshift.io/issues/3662

fix(improvement): Reverted the code to allow diff app and repo name

---

src/app/launcher/launcher.module.ts
src/demo/app.module.ts

BREAKING-CHANGE:
- Broadcaster need to be provided by container app (demo, frontend, fabric8-ui)

fix: make Broadcaster provided by container app

---

package-lock.json
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.spec.ts
src/app/launcher/service/mission-runtime.service.spec.ts
src/app/launcher/service/mission-runtime.service.ts

Fix bug in `getAvailableBoostersa` algo thanks to tests.
Closes #262

fix: Add unit tests for MissionRuntimeService and fix a bug

---

index.ts
package.json
src/app/launcher/create-app/dependency-editor-step/dependency-editor-step.component.spec.ts
src/app/launcher/create-app/dependency-editor-step/dependency-editor-step.component.ts
src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.spec.ts
src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.ts
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.spec.ts
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.ts
src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.spec.ts
src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.ts
src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.spec.ts
src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.spec.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.ts
src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.spec.ts
src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.ts
src/app/launcher/launcher.component.spec.ts
src/app/launcher/launcher.component.ts
src/app/launcher/step-indicator/step-indicator.component.ts

user story :- https://github.com/openshiftio/openshift.io/issues/3241

fix(telemetry): Added code for telemetry

---

index.ts
package.json
src/app/launcher/create-app/dependency-editor-step/dependency-editor-step.component.spec.ts
src/app/launcher/create-app/dependency-editor-step/dependency-editor-step.component.ts
src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.spec.ts
src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.ts
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.spec.ts
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.ts
src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.spec.ts
src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.ts
src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.spec.ts
src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.spec.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.ts
src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.spec.ts
src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.ts
src/app/launcher/launcher.component.spec.ts
src/app/launcher/launcher.component.ts
src/app/launcher/step-indicator/step-indicator.component.ts

Reverts fabric8-launcher/ngx-launcher#273

Revert "fix(telemetry): Added code for telemetry"

---

package-lock.json
package.json
src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.spec.ts
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.spec.ts
src/app/launcher/create-app/release-strategy-createapp-step/release-strategy-createapp-step.component.spec.ts
src/app/launcher/import-app/release-strategy-importapp-step/release-strategy-importapp-step.component.spec.ts
src/app/launcher/launcher.module.ts

Removes deprecated and unused patternfly-ng module imports.
Resolves openshiftio/openshift.io#2704

patternfly-ng: remove deprecations

---

src/app/launcher/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.html
src/app/launcher/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.less
src/app/launcher/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.spec.ts
src/app/launcher/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.ts
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.ts
src/app/launcher/import-app/project-progress-importapp-nextstep/project-progress-importapp-nextstep.component.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.ts
src/app/launcher/launcher.component.ts
src/app/launcher/model/progress.model.ts
src/app/launcher/service/dependency-check.service.ts
src/app/launcher/service/project-summary.service.ts
src/demo/service/demo-dependency-check.service.ts
src/demo/service/demo-project-progress.service.ts
src/demo/service/demo-project-summary.service.ts

fixes: https://github.com/fabric8-launcher/ngx-launcher/issues/239

created retry button on progress screen

---

src/app/launcher/shared/telemetry.decorator.ts

fixes this https://github.com/fabric8-launcher/ngx-launcher/issues/288

fix(injector): Get the injector instance if available

---

package.json

this PR is towards fixing this issue https://github.com/openshiftio/openshift.io/issues/3833

fix(version-fix): remvoed the caret in version

---

src/app/launcher/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.html
src/app/launcher/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.ts

https://files.slack.com/files-pri/T1ZUKET9V-FBBDXMV44/screenshot_from_2018-06-21_11-03-04.png

fix: reset error message on retry

---

src/app/launcher/create-app/dependency-editor-step/dependency-editor-step.component.html

Tracks: https://github.com/openshiftio/openshift.io/issues/3809

fix(scroll): handles the scroll issue that happens with dependency editor

---

src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts
src/app/launcher/shared/properties.spec.ts
src/app/launcher/shared/properties.ts
src/app/launcher/shared/telemetry.decorator.ts

fixing issue: https://github.com/fabric8-launcher/launcher-frontend/issues/519

fix: issue issue

---

src/app/launcher/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.html

fixes: https://github.com/fabric8-launcher/launcher-frontend/issues/520

fix: show progress icon

---

package-lock.json
package.json

fix(ux): handles styles on click, handles count of all categories
fix(styles): addresses minor alignment and style related bugs. 
fix(style): changes the background style of the header.

fix(version): updates fabric8-analytics-dependency-editor to 0.0.27

---

src/app/launcher/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.ts
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.ts
src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.ts
src/app/launcher/import-app/project-summary-importapp-step/project-summary-importapp-step.component.ts
src/app/launcher/shared/properties.spec.ts
src/app/launcher/shared/properties.ts

- Get the broadcast event data as a flat json object as expected by the Woopra api.
- Updated some specs

fix(telemetry): get the event data as a flat json object

---

src/app/launcher/create-app/link-accounts-createapp-step/link-accounts-createapp-step.component.ts
src/demo/service/demo-token.service.ts

fix: cluster autoselect

---

package-lock.json
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.spec.ts
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts
src/app/launcher/service/mission-runtime.service.spec.ts
src/app/launcher/service/mission-runtime.service.ts

feat: in MissionRuntime step, auto select the most compatible version

---

src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.html
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.less
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.model.ts
src/assets/mock/demo-catalog-launch.json
src/assets/mock/demo-catalog-osio.json

- sort cluster incompatible mission at the bottom
- shrink incompatible mission
- update boosters demo data for launch and osio
Fixes https://github.com/fabric8-launcher/launcher-frontend/issues/390

feat: nicer mission selection for launch flow

---

src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.html

fix (runtime): dropdown now collapses when the user chose a version

---

package-lock.json
package.json

Tracks: https://github.com/openshiftio/openshift.io/issues/3863

fix(version): updates fabric8-analytics-dependency-editor to 0.6.3

---

index.ts
package-lock.json
package.json
src/app/launcher/create-app/dependency-editor-step/dependency-editor-step.component.html
src/app/launcher/create-app/dependency-editor-step/dependency-editor-step.component.spec.ts
src/app/launcher/create-app/dependency-editor-step/dependency-editor-step.component.ts
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts
src/app/launcher/create-app/project-summary-createapp-step/project-summary-createapp-step.component.ts
src/app/launcher/launcher.module.ts
src/app/launcher/model/mission.model.ts
src/app/launcher/service/dependency-editor.service.ts
src/demo/service/demo-dependency-editor.service.ts
src/demo/service/demo-mission-runtime.service.ts
src/demo/service/demo-project-summary.service.ts
tsconfig-aot.json
tsconfig.json

Tracks : 
- https://github.com/openshiftio/openshift.io/issues/3244
Depends on : 
- https://github.com/fabric8-analytics/fabric8-analytics-dependency-editor/pull/105

Blank mission support for dependency editor

---

src/app/launcher/create-app/targetenvironment-createapp-step/target-environment-createapp-step.component.html
src/app/launcher/create-app/targetenvironment-createapp-step/target-environment-createapp-step.component.less

to test empty [demo-token.json](tree/master/src/assets/mock) 
fixes: https://github.com/fabric8-launcher/launcher-frontend/issues/498

fix (target-env): added link to create / setup cluster

---

src/app/launcher/create-app/activate-booster-createapp-nextstep/activate-booster-createapp-nextstep.component.html
src/app/launcher/import-app/project-progress-importapp-nextstep/project-progress-importapp-nextstep.component.html

fix: fix typo in ZIP download

---

src/app/launcher/shared/telemetry.decorator.ts

- Improved the broadcasting event for telemetry.
- Added a single event name for all the analytics tracking user events.

fix(telemetry): improvised the telemetry event

---

package-lock.json
package.json

- Updates version of dep-editor to 0.7.5
- Handles the data changes for the 'Wildfly-swarm'

fix(version): version upgrade for dep-editor

---

src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.html
src/app/launcher/import-app/gitprovider-importapp-step/gitprovider-importapp-step.component.less

Issue - https://github.com/openshiftio/openshift.io/issues/3927

fix(gitprovider-importapp): show all GitHub repositories  in dropdown

---

src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.html
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.spec.ts
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.component.ts
src/app/launcher/create-app/mission-runtime-createapp-step/mission-runtime-createapp-step.model.ts

fix: Some missions are not selectable when runtime is selected

---

projects/ngx-launcher/src/lib/create-app/link-accounts-createapp-step/link-accounts-createapp-step.component.html

fix: hide cluster select when there is only one cluster

---

package-lock.json
projects/ngx-launcher/src/lib/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.html
projects/ngx-launcher/src/lib/create-app/project-progress-createapp-nextstep/project-progress-createapp-nextstep.component.ts
projects/ngx-launcher/src/lib/import-app/project-progress-importapp-nextstep/project-progress-importapp-nextstep.component.html
projects/ngx-launcher/src/lib/import-app/project-progress-importapp-nextstep/project-progress-importapp-nextstep.component.ts
src/app/service/demo-project-progress.service.ts
src/app/service/demo-project-summary.service.ts

Fixes https://github.com/fabric8-launcher/launcher-frontend/issues/663

fix: refactor code and fix progress null after retry bug

---

projects/ngx-launcher/src/lib/create-app/link-accounts-createapp-step/link-accounts-createapp-step.component.html
projects/ngx-launcher/src/lib/create-app/link-accounts-createapp-step/link-accounts-createapp-step.component.less
projects/ngx-launcher/src/lib/create-app/targetenvironment-createapp-step/target-environment-createapp-step.component.html
projects/ngx-launcher/src/lib/create-app/targetenvironment-createapp-step/target-environment-createapp-step.component.less

Fixes https://github.com/fabric8-launcher/launcher-frontend/issues/662

fix: make cluster selection nicer

---

projects/ngx-launcher/src/assets/stylesheets/shared/_cards.less
projects/ngx-launcher/src/lib/create-app/project-summary-createapp-step/project-summary-createapp-step.component.html

fix: uses the space in the box better to prevent overflow

---

projects/ngx-launcher/package-lock.json
projects/ngx-launcher/package.json

- updates dep-editor version to 1.0.3
Tracks : 
- https://github.com/openshiftio/openshift.io/issues/4380

fix(dependency-editor): updates dep-editor version

---

projects/ngx-launcher/src/lib/create-app/gitprovider-createapp-step/gitprovider-createapp-step.component.html

issue - https://github.com/openshiftio/openshift.io/issues/4142

fix(gitprovider): show error message if repository name is not available

---

projects/ngx-launcher/src/lib/components/mission-runtime-step/mission-runtime-review.component.html

fix(summary): Do not show undefined icons

---

projects/ngx-launcher/src/lib/components/runtime-step/runtime-step.component.html
projects/ngx-launcher/src/lib/components/runtime-step/runtime-step.component.ts
projects/ngx-launcher/src/lib/model/runtime.model.ts
projects/ngx-launcher/src/lib/service/app-creator.service.ts
src/app/mock/demo-capability-enums.json
src/app/service/demo-app-creator.service.ts

PR to support: https://github.com/fabric8-launcher/launcher-creator-backend/pull/86 @quintesse

feat: added runtime version support

---

src/app/service/demo-app-creator.service.ts

fixes 3. on this [quick list](https://hackmd.io/ZqdrmwEeSSKLYKpRtuTS4A)

fix: set initial default value for properties

---

projects/ngx-launcher/src/lib/components/mission-runtime-step/mission-runtime-step.component.ts
projects/ngx-launcher/src/lib/components/targetenvironment-step/target-environment-step.component.spec.ts
projects/ngx-launcher/src/lib/components/targetenvironment-step/target-environment-step.component.ts
src/app/launcher-app/launcher-app.component.html
src/app/service/demo-app-creator.service.ts
src/app/service/demo-dependency-check.service.ts

Maven default should now be `com.yourcompany:newapp` and added a small fix for
when selecting node.js

Updated maven defaults + some small fixes

---

projects/ngx-launcher/src/lib/components/capabilities-step/capabilities-step.component.ts
projects/ngx-launcher/src/lib/components/runtime-step/runtime-step.component.html
projects/ngx-launcher/src/lib/components/runtime-step/runtime-step.component.ts
projects/ngx-launcher/src/lib/components/targetenvironment-step/target-environment-step.component.ts
src/app/mock/demo-capabilities.json

During integration test yesterday these issues where discovered.

Fixed some small integration test issue

---

projects/ngx-launcher/src/lib/components/activate-booster-nextstep/activate-booster-nextstep.component.html
projects/ngx-launcher/src/lib/components/runtime-step/runtime-step.component.ts
projects/ngx-launcher/src/lib/launcher.component.html
src/app/service/demo-project-progress.service.ts

fixing: https://github.com/fabric8-launcher/launcher-frontend/issues/784

fix: adds general button to nextstep

---

projects/ngx-launcher/src/lib/components/project-progress-nextstep/project-progress-nextstep.component.html

fixes: https://github.com/fabric8-launcher/launcher-frontend/issues/789

fix: removed static html

---

projects/ngx-launcher/src/lib/components/frontend-step/frontend-step.component.html
projects/ngx-launcher/src/lib/components/runtime-step/runtime-step.component.html

fixes: https://github.com/fabric8-launcher/launcher-frontend/issues/808

fix: card-size on small and large screens

---

projects/ngx-launcher/src/lib/components/runtime-step/runtime-step.component.html
projects/ngx-launcher/src/lib/components/runtime-step/runtime-step.component.less

fixing: https://github.com/fabric8-launcher/ngx-launcher/issues/551

fix: card sizes

---

projects/ngx-launcher/src/lib/components/frontend-step/frontend-step.component.ts

fixes: https://github.com/fabric8-launcher/launcher-frontend/issues/815

fix: framework name added

---

README.md
package.json
projects/ngx-launcher/karma.conf.js

This PR does:
- add a target to easy unit test debugging. 
- update the README with usage.

clean: provide target for running unit test in debug mode

---

projects/ngx-launcher/src/lib/components/gitprovider-step/gitprovider-step.component.ts
projects/ngx-launcher/src/lib/step-indicator/step-indicator.component.ts

fix: watch changes to project name and update git repo if default

---

projects/ngx-launcher/src/lib/components/gitprovider-step/gitprovider-step.component.html
projects/ngx-launcher/src/lib/components/gitprovider-step/gitprovider-step.component.less
projects/ngx-launcher/src/lib/components/gitprovider-step/gitprovider-step.component.spec.ts
projects/ngx-launcher/src/lib/components/gitprovider-step/gitprovider-step.component.ts
projects/ngx-launcher/src/lib/components/release-strategy-step/release-strategy-step.component.spec.ts
projects/ngx-launcher/src/lib/components/release-strategy-step/release-strategy-step.component.ts
projects/ngx-launcher/src/lib/model/build-tool.model.ts
projects/ngx-launcher/src/lib/service/git-provider.service.ts
projects/ngx-launcher/src/public_api.ts
src/app/app.module.ts
src/app/service/demo-git-provider.service.ts
src/app/shared/build-tool-detector-api-url.ts

This PR adds a build tool detector in the import flow. After importing the project we detect the build tool and as per build tool detection, we show the pipeline.
Story: https://openshift.io/openshiftio/Openshift_io/plan/detail/404

Build tool detector

---

projects/ngx-launcher/src/lib/components/project-summary-step/project-summary-step.component.ts
projects/ngx-launcher/src/lib/model/projectile.model.ts
projects/ngx-launcher/src/lib/step-indicator/step-indicator.component.ts

@vikram-raj this makes things a bit more readable I think

fix: better state analytics broadcast

---

projects/ngx-launcher/src/lib/model/projectile.model.ts

Need this changes to fix this issue https://github.com/openshiftio/openshift.io/issues/4569

fix: add resetState function in projectile model

---

projects/ngx-launcher/src/lib/model/projectile.model.spec.ts
projects/ngx-launcher/src/lib/model/projectile.model.ts

fixes: https://github.com/fabric8-launcher/launcher-frontend/issues/1126

fix: don't rename url parameters for shared state
